#!/usr/bin/env bash
# Changes localhost to 127.0.0.2 and facebook.com to 8.8.8.8

sed 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts > /tmp/hosts
cat /tmp/hosts > /etc/hosts
grep -q "^8.8.8.8[[:space:]]\+facebook.com" /etc/hosts || echo "8.8.8.8 facebook.com" >> /etc/hosts
